DB_NAME='postgres'
DB_USER='postgres'
DB_PASSWORD='l9Yz2BavPQFaV6waT6UVWhzdU9X9gv7VmaWlri8CtfHbQBU4Ra8eS7gQd0JjZDkJ'
DB_HOST='69.62.124.103'
WEB_PASS="Akhand_Voter"
IMGBB_API_KEY="ec519cb1c1643a46e16f22fe58a256cb"
